hooks:
  waitingAndDelete:
    - webDriver: AccessNewUrl # chụp màng hình
      description: 'Truy cập list Server'
      newUrl: 'https://portal3.vngcloud.vn/servers/list.html'
    - webDriver: SleepAction #set timeout bắt element
      description: 'Thực hiện Sleep trong 10s'
      timeout: 10
    - webDriver: SetImplicitWaitTimeout #set timeout bắt element
      description: 'Thực hiện Implicit Wait Timeout trong vòng 60s'
      timeout: 60
    - webDriver: FindElement
      description: 'Tìm VM mà ta muốn' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: 'input[ng-model="filterSearchText"]'
        ignored: False
      actions:
        - action: Sendkeys #đánh chữ vào ô input
          value: 'Ubuntu-SE-Random'
    - webDriver: FindElement
      description: 'Check VM có trong List không' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//p[contains(text(),"Ubuntu-SE-Random")]'
        ignored: True
      actions:
        - action: Text
    - webDriver: FindElement
      description: 'Click checkbox VM' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//p[contains(text(),"Ubuntu-SE-Random")]//parent::div//preceding-sibling::div//label/span'
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: FindElement
      description: 'Click vào Action' 
      webElement: 
        by: ByXPATH #tìm kí tự mong muốn
        value: '//span[contains(text(),"Action")]'
        ignored: True
      actions:
        - action: Click
    - webDriver: FindElement
      description: 'Click Delete VM trong Action' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: "a#delete-server-btn"
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: FindElement
      description: 'Click Delete VM trong Action' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: 'a[ng-click="deleteServers()"]'
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input
    - webDriver: SleepAction #set timeout bắt element
      description: 'Thực hiện Sleep trong 120s'
      timeout: 120
    - webDriver: FindElement
      description: 'Click thùng rác' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: 'span.headerNumber.trashItemNumber'
        ignored: True
      actions:
        - action: Click #đánh chữ vào ô input  
    - webDriver: ExecuteScript
      description: 'Click Delete VM trong thùng rác'
      script: document.querySelector('tr[resourcename="Ubuntu-SE-Random"]>td#doDelete>i.fa-trash').click()
    - webDriver: FindElement
      description: 'Click Confirm Delete VM trong thùng rác' 
      webElement: 
        by: ByCSSSelector #tìm kí tự mong muốn
        value: '.btn-accept-remove-resource'
        ignored: True
      actions:
        - action: Click
    - webDriver: SleepAction #set timeout bắt element
      description: 'Thực hiện Sleep trong 20s'
      timeout: 20
